package com.puttysoftware.sandbox;

public enum SystemDir {
    LIBRARY,
    DOCUMENTS,
    CACHES,
    APPLICATION_SUPPORT,
    APPLICATION,
    AUTOSAVED_INFORMATION,
    DESKTOP,
    DOWNLOADS,
    MOVIES,
    MUSIC,
    PICTURES,
    SHARED_PUBLIC,
    SYSTEM_LIBRARY,
    SYSTEM_APPLICATION_SUPPORT,
    SYSTEM_CACHES,
    SYSTEM_APPLICATION,
    SYSTEM_USER,
    USER_HOME
}
